<a href="https://colab.research.google.com/github/Maks6666/ML/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модуля pandas

In [1]:
import pandas as pd

Дані про пасажирів корабля:
* pclass -- клас білета(перший, другий або третій)
* sex -- стать
* age -- вік
* sibsp -- кількість братів\сестер та чоловіків\дружин на борту
* parch -- кількість дітей та батьків на борту
* fare -- вартість поїздки
* embarked -- Порт посадки (C = Шербур, Q = Квінстаун, S = Саутгемптон)

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/ship_passengers.csv",
                 index_col="Unnamed: 0")

In [16]:
df

     pclass     sex   age  sibsp  parch     fare embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [9]:
print(f'{df.info()}\n')
print(f'{df.columns}\n')
print(f'{df.isnull().sum()}')

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   embarked  889 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 55.7+ KB
None

Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked'], dtype='object')

pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

# Завдання 2
Скільки пасажирів сіло у Квінстауні?

In [15]:
pass_ammount = df.shape[0]
pass_ammount

891

# Завдання 3
Виведіть стать, вік та вартість поїздки для пасажирів з білетом першого класу

In [19]:
new_df = df[df["pclass"] == 1]
new_df[["sex", "age", "fare"]]

        sex   age     fare
1    female  38.0  71.2833
3    female  35.0  53.1000
6      male  54.0  51.8625
11   female  58.0  26.5500
23     male  28.0  35.5000
..      ...   ...      ...
871  female  47.0  52.5542
872    male  33.0   5.0000
879  female  56.0  83.1583
887  female  19.0  30.0000
889    male  26.0  30.0000

[216 rows x 3 columns]

# Завдання 4
Ввиведіть дані про неповнолітніх чоловіків з Шербура

In [23]:
df[(df["age"] < 18) & (df["sex"] == "male") & (df["embarked"] == "S")]

     pclass   sex    age  sibsp  parch      fare embarked
7         3  male   2.00      3      1   21.0750        S
50        3  male   7.00      4      1   39.6875        S
59        3  male  11.00      5      2   46.9000        S
63        3  male   4.00      3      2   27.9000        S
78        2  male   0.83      0      2   29.0000        S
86        3  male  16.00      1      3   34.3750        S
138       3  male  16.00      0      0    9.2167        S
163       3  male  17.00      0      0    8.6625        S
164       3  male   1.00      4      1   39.6875        S
165       3  male   9.00      0      2   20.5250        S
182       3  male   9.00      4      2   31.3875        S
183       2  male   1.00      2      1   39.0000        S
193       2  male   3.00      1      1   26.0000        S
220       3  male  16.00      0      0    8.0500        S
261       3  male   3.00      4      2   31.3875        S
266       3  male  16.00      4      1   39.6875        S
282       3  male  16.00      0      0    9.5000        S
305       1  male   0.92      1      2  151.5500        S
333       3  male  16.00      2      0   18.0000        S
340       2  male   2.00      1      1   26.0000        S
348       3  male   3.00      1      1   15.9000        S
386       3  male   1.00      5      2   46.9000        S
407       2  male   3.00      1      1   18.7500        S
433       3  male  17.00      0      0    7.1250        S
445       1  male   4.00      0      2   81.8583        S
480       3  male   9.00      5      2   46.9000        S
489       3  male   9.00      1      1   15.9000        S
500       3  male  17.00      0      0    8.6625        S
549       2  male   8.00      1      1   36.7500        S
574       3  male  16.00      0      0    8.0500        S
683       3  male  14.00      5      2   46.9000        S
686       3  male  14.00      4      1   39.6875        S
721       3  male  17.00      1      0    7.0542        S
746       3  male  16.00      1      1   20.2500        S
751       3  male   6.00      0      1   12.4750        S
755       2  male   0.67      1      1   14.5000        S
764       3  male  16.00      0      0    7.7750        S
788       3  male   1.00      1      2   20.5750        S
791       2  male  16.00      0      0   26.0000        S
802       1  male  11.00      1      2  120.0000        S
819       3  male  10.00      3      2   27.9000        S
824       3  male   2.00      4      1   39.6875        S
831       2  male   0.83      1      1   18.7500        S
841       2  male  16.00      0      0   10.5000        S
844       3  male  17.00      0      0    8.6625        S
850       3  male   4.00      4      2   31.2750        S
869       3  male   4.00      1      1   11.1333        S

# Завдання 5
Створіть новий стовпчик relatives -- загальна кількість родичів на борту для кожного пасажира

In [27]:
df["relatives"] = df["parch"] + df["sibsp"]
df

     pclass     sex   age  sibsp  parch     fare embarked  relatives
0         3    male  22.0      1      0   7.2500        S          1
1         1  female  38.0      1      0  71.2833        C          1
2         3  female  26.0      0      0   7.9250        S          0
3         1  female  35.0      1      0  53.1000        S          1
4         3    male  35.0      0      0   8.0500        S          0
..      ...     ...   ...    ...    ...      ...      ...        ...
886       2    male  27.0      0      0  13.0000        S          0
887       1  female  19.0      0      0  30.0000        S          0
888       3  female   NaN      1      2  23.4500        S          3
889       1    male  26.0      0      0  30.0000        C          0
890       3    male  32.0      0      0   7.7500        Q          0

[891 rows x 8 columns]

# Завдання 6
Видаліть стовпчик, в якому найбільше пропусків. Якщо пропущені значення ще залишаться, видаліть рядки з пропусками

In [29]:
df = df.drop("age", axis='columns')
df

     pclass     sex  sibsp  parch     fare embarked  relatives
0         3    male      1      0   7.2500        S          1
1         1  female      1      0  71.2833        C          1
2         3  female      0      0   7.9250        S          0
3         1  female      1      0  53.1000        S          1
4         3    male      0      0   8.0500        S          0
..      ...     ...    ...    ...      ...      ...        ...
886       2    male      0      0  13.0000        S          0
887       1  female      0      0  30.0000        S          0
888       3  female      1      2  23.4500        S          3
889       1    male      0      0  30.0000        C          0
890       3    male      0      0   7.7500        Q          0

[891 rows x 7 columns]

In [34]:
missing_embarked = df['embarked'].isnull()
df = df[~missing_embarked]
df.isnull().sum()

pclass       0
sex          0
sibsp        0
parch        0
fare         0
embarked     0
relatives    0
dtype: int64